version: "3.8"

services:
  db:
    image: postgres:15.3
    container_name: pg_db_gopayments
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: andrey
      POSTGRES_PASSWORD: secret
      POSRGRES_DB: gopayments
    volumes:
      - ./data/local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin_gopayments
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: email@nvim-btw.com
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin_data:
